#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION "2019.3.2f1"
#define UNITY_VERSION_DIGITS "2019.3.2"
#define UNITY_VERSION_SUFFIX "f1"
#define UNITY_VERSION_VER 2019
#define UNITY_VERSION_MAJ 3
#define UNITY_VERSION_MIN 2
#define UNITY_IS_BETA 0
